### ISSUE TITLE
Racey behavior?

### ISSUE THREAD

**Issue by binary132** [gdamore/mangos#147] opened 2015-09-30 13:55 UTC
Steps to reproduce: 
 - run `go test -race ./...` a few times in `github.com/gdamore/mangos/`.
 - Should present as test failures with no races detected.

Tested on:
 - go1.5.1 linux/amd64
 - go1.5 darwin/amd64

---

I'm trying to debug some Heisenbugs in my test suite, which passes on my Linux machine with `go test`, but almost always fails when I invoke it with `go test -race`.  What's strange is that no races are detected.  It always fails on MacOS.

It appears that when I use `pub.Close()` it doesn't always free the TCP port or IPC resource (only testing on TCP and IPC.)  I'm getting `bind: address already in use` on Connect / Listen.

I decided to dig into mangos a bit to see whether I could reproduce this behavior in mangos itself.  Again, when running with go test, the tests all pass.  But when running with `go test -race ./...`, I am getting failures in porthook_test and common_test which seem "non-deterministic" even though the race checker does not show any races.  That is, sometimes some tests fail, while others do not fail.

These are all pastes of the mangos suite using `go test -race` invoked the same way from the package root:
 - [No failures at all](http://pastebin.centos.org/34816/)
 - [`porthook_test` failure only](http://pastebin.centos.org/34806/)
 - [`common_test` failure only](http://pastebin.centos.org/34821/)
 - [failure in both `porthook_test` and `common_test`](http://pastebin.centos.org/34811/)

**Comment by gdamore** [comment] 2015-09-30 19:23
These aren't "races" in mangos per se.  There are some problems with test fragility with -race, mostly because -race makes the test take a lot longer.

The porthook test is known to fail occasionally especially in this situation -- the test has an "intrisic" race (one not caught by -race, but an artifact of how it tests the hooks) and the common_test failure you saw is a WSS failure again most likely caused by the -race making the code take too long.

In particular, if we see backpressure because one side takes too long, the message can be deferred or dropped; it will be replayed later, but the increase in time means that the test timeouts will fire before the test completes.

Arguably, my tests should be made a bit more robust, but I actually prefer that they be fragile in this way -- if we wind up relaxing the timeouts, that could lead to regressions in normal mode, that hurt performance badly.  (E.g. imagine a case where I dropped every other packet.  We'd want to catch that and flag it, not have it get suppressed by long timeouts and automatic retry!)

**Comment by gdamore** [comment] 2015-09-30 19:39
I'm going to close this, because it doesn't actually represent a "bug" per se, just conditions in which the tests are too stringent to be used safely with -race.

I do test with -race from time to time, but only to detect actual race conditions.  Unless it reports a race condition, I don't consider problems like this found with -race to be real problems unless they reproduce also without -race.

**Closed by gdamore** 2015-09-30 19:39 UTC
